//***********************************************************
//* MomentumSolverGUI.java Created By Kian Gorgichuk        *
//* Copyright (c) 2014 Kian Gorgichuk. All rights reserved. *
//***********************************************************

package mainpkg;

//Imports
import menu.AboutListenerMac;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import javax.swing.JRootPane;
import javax.swing.UIManager;
import javax.swing.*;

//Creates JFrame for GUI (After Collision Objects A & B DO NOT Fuse Together)
public class MomentumSolverGUI extends javax.swing.JFrame {
    
//Custom Variables
    //Menu Bar Variables
    private JMenuBar _menuBar = null;
    private JMenu _infoMenu = null;
    private JMenuItem _aboutItem = null;
    private JMenuItem _helpItem = null;
    
    private boolean _isMacOS = false;
    
    /**
     * Creates new form MomentumSolverGUI
     */
    public MomentumSolverGUI() {
        String osName = System.getProperty("os.name").toLowerCase();
        _isMacOS = osName.contains("os x");
       
        //Create Menu Bar - OS Specific
         if(_isMacOS) //Mac OS X Specific
         {
            //Set GUI to Mac OS X Feel in Order to Get MenuBar On Top
             try{ UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); }
            catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
            {
                JOptionPane.showMessageDialog(null, ex.toString(), "Error!",  JOptionPane.ERROR_MESSAGE);
			System.err.println(ex.toString()); 
            } //Show Pop-up Alert and Print Out Error to Console
            _menuBar = new JMenuBar();
            _infoMenu = new JMenu("Information");
            _helpItem = new JMenuItem("Help");
            _infoMenu.add(_helpItem);
            _menuBar.add(_infoMenu);
         }
         else //Other Operating Systems
         {
             _menuBar = new JMenuBar();
             _infoMenu = new JMenu("Information");
             _aboutItem = new JMenuItem("About"); 
             _helpItem = new JMenuItem("Help");
             _infoMenu.add(_aboutItem);
            _infoMenu.add(_helpItem);
            _menuBar.add(_infoMenu);
         }
        
        //Wire Up MenuBar
        initMenuBar();
        
        this.setJMenuBar(_menuBar);
        
        //Change Look and Feel to Nimbus
        try{ UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); }
        catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error!",  JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.toString()); 
        } //Show Pop-up Alert and Print Out Error to Console
        
        //JFrame Properties Setup
        //Setup Image Icon - Windows Only
        ImageIcon img = new ImageIcon(getClass().getResource("icon.png"));
        this.setIconImage(img.getImage());
        
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        Color backgroundColor = new Color(239,243,249);
        this.getContentPane().setBackground(backgroundColor);
        initComponents(); //To JFrame
        this.getRootPane().setDefaultButton(calculateBtn);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whichCalcGroup = new javax.swing.ButtonGroup();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        panelA = new javax.swing.JPanel();
        massALabel = new javax.swing.JLabel();
        massATextField = new javax.swing.JTextField();
        massAUnitsLabel = new javax.swing.JLabel();
        vectorInitACalcBtn = new javax.swing.JRadioButton();
        veloInitATextField = new javax.swing.JTextField();
        veloInitAUnitLabel = new javax.swing.JLabel();
        dirInitATextField = new javax.swing.JTextField();
        dirInitAUnitLabel = new javax.swing.JLabel();
        vectorFinACalcBtn = new javax.swing.JRadioButton();
        veloFinAUnitLabel = new javax.swing.JLabel();
        veloFinATextField = new javax.swing.JTextField();
        dirFinATextField = new javax.swing.JTextField();
        dirFinAUnitLabel = new javax.swing.JLabel();
        panelB = new javax.swing.JPanel();
        massBLabel = new javax.swing.JLabel();
        massBTextField = new javax.swing.JTextField();
        massBUnitsLabel = new javax.swing.JLabel();
        vectorInitBCalcBtn = new javax.swing.JRadioButton();
        veloInitBTextField = new javax.swing.JTextField();
        veloInitBUnitLabel = new javax.swing.JLabel();
        dirInitBTextField = new javax.swing.JTextField();
        dirInitBUnitLabel = new javax.swing.JLabel();
        vectorFinBCalcBtn = new javax.swing.JRadioButton();
        veloFinBTextField = new javax.swing.JTextField();
        veloFinBUnitLabel = new javax.swing.JLabel();
        dirFinBTextField = new javax.swing.JTextField();
        dirFinBUnitLabel = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();

        whichCalcGroup.add(vectorInitACalcBtn);
        whichCalcGroup.add(vectorFinACalcBtn);
        whichCalcGroup.add(vectorInitBCalcBtn);
        whichCalcGroup.add(vectorFinBCalcBtn);

        setTitle("2D Momentum Solver ");

        titlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        titleLabel.setText("2D Momentum Solver");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        panelA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        massALabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        massALabel.setText("Mass A:");

        massATextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        massAUnitsLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        massAUnitsLabel.setText("kg");

        vectorInitACalcBtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        vectorInitACalcBtn.setText("Initial Vector for Object A :");
        vectorInitACalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSelected(evt);
            }
        });

        veloInitATextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        veloInitATextField.setEnabled(false);

        veloInitAUnitLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        veloInitAUnitLabel.setText("m/s");

        dirInitATextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        dirInitATextField.setEnabled(false);

        dirInitAUnitLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dirInitAUnitLabel.setText("degrees");

        vectorFinACalcBtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        vectorFinACalcBtn.setText("Post Collision Vector for Object A :");
        vectorFinACalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSelected(evt);
            }
        });

        veloFinAUnitLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        veloFinAUnitLabel.setText("m/s");

        veloFinATextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        dirFinATextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        dirFinAUnitLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dirFinAUnitLabel.setText("degrees");

        javax.swing.GroupLayout panelALayout = new javax.swing.GroupLayout(panelA);
        panelA.setLayout(panelALayout);
        panelALayout.setHorizontalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vectorInitACalcBtn)
                    .addComponent(vectorFinACalcBtn)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dirFinATextField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(veloFinATextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dirInitATextField)
                            .addComponent(veloInitATextField))
                        .addGap(3, 3, 3)
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(veloInitAUnitLabel)
                            .addComponent(veloFinAUnitLabel)
                            .addComponent(dirInitAUnitLabel)
                            .addComponent(dirFinAUnitLabel)))
                    .addGroup(panelALayout.createSequentialGroup()
                        .addComponent(massALabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(massATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(massAUnitsLabel)))
                .addGap(5, 5, 5))
        );
        panelALayout.setVerticalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(massALabel)
                    .addComponent(massATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(massAUnitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vectorInitACalcBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veloInitATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veloInitAUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirInitATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirInitAUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vectorFinACalcBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veloFinATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veloFinAUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirFinATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirFinAUnitLabel))
                .addGap(5, 5, 5))
        );

        vectorInitACalcBtn.setSelected(true);

        panelB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelB.setPreferredSize(new java.awt.Dimension(325, 258));

        massBLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        massBLabel.setText("Mass B:");

        massBTextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        massBUnitsLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        massBUnitsLabel.setText("kg");

        vectorInitBCalcBtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        vectorInitBCalcBtn.setText("Initial Vector for Object B :");
        vectorInitBCalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSelected(evt);
            }
        });

        veloInitBTextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        veloInitBUnitLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        veloInitBUnitLabel.setText("m/s");

        dirInitBTextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        dirInitBUnitLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dirInitBUnitLabel.setText("degrees");

        vectorFinBCalcBtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        vectorFinBCalcBtn.setText("Post Collision Vector for Object B :");
        vectorFinBCalcBtn.setToolTipText("");
        vectorFinBCalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSelected(evt);
            }
        });

        veloFinBTextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        veloFinBUnitLabel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        veloFinBUnitLabel.setText("m/s");

        dirFinBTextField.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        dirFinBUnitLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dirFinBUnitLabel.setText("degrees");

        javax.swing.GroupLayout panelBLayout = new javax.swing.GroupLayout(panelB);
        panelB.setLayout(panelBLayout);
        panelBLayout.setHorizontalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addComponent(massBLabel)
                        .addGap(2, 2, 2)
                        .addComponent(massBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(massBUnitsLabel))
                    .addComponent(vectorFinBCalcBtn)
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dirFinBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(veloFinBTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dirInitBTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(veloInitBTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(3, 3, 3)
                        .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(veloInitBUnitLabel)
                            .addComponent(dirInitBUnitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(veloFinBUnitLabel)
                            .addComponent(dirFinBUnitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(vectorInitBCalcBtn))
                .addGap(5, 5, 5))
        );
        panelBLayout.setVerticalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(massBLabel)
                    .addComponent(massBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(massBUnitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vectorInitBCalcBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veloInitBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veloInitBUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirInitBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirInitBUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vectorFinBCalcBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veloFinBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veloFinBUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirFinBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirFinBUnitLabel))
                .addGap(5, 5, 5))
        );

        calculateBtn.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        calculateBtn.setText("Calculate Answer");
        calculateBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calculateBtn.setMaximumSize(new java.awt.Dimension(142, 39));
        calculateBtn.setMinimumSize(new java.awt.Dimension(142, 39));
        calculateBtn.setPreferredSize(new java.awt.Dimension(142, 39));
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.setMaximumSize(new java.awt.Dimension(142, 39));
        mainMenuBtn.setMinimumSize(new java.awt.Dimension(142, 39));
        mainMenuBtn.setPreferredSize(new java.awt.Dimension(142, 39));
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuRequested(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSelected
       //Enable Textboxes All Buttons
        veloInitATextField.setEnabled(true);
        dirInitATextField.setEnabled(true);
        
        veloInitBTextField.setEnabled(true);
        dirInitBTextField.setEnabled(true);
        
        veloFinATextField.setEnabled(true);
        dirFinATextField.setEnabled(true);
        
        veloFinBTextField.setEnabled(true);
        dirFinBTextField.setEnabled(true);
       
        //Disable Selected Textboxes and Clear Their Values
        if(vectorInitACalcBtn.isSelected())
        {
            veloInitATextField.setEnabled(false);
            dirInitATextField.setEnabled(false);
            veloInitATextField.setText("");
            dirInitATextField.setText("");
        }
        else if(vectorInitBCalcBtn.isSelected())
        {
             veloInitBTextField.setEnabled(false);
             dirInitBTextField.setEnabled(false);
             veloInitBTextField.setText("");
             dirInitBTextField.setText("");
        }
        else if(vectorFinACalcBtn.isSelected())
        {
            veloFinATextField.setEnabled(false);
            dirFinATextField.setEnabled(false);
            veloFinATextField.setText("");
            dirFinATextField.setText("");
        }
        else
        {
            veloFinBTextField.setEnabled(false);
            dirFinBTextField.setEnabled(false);
            veloFinBTextField.setText("");
            dirFinBTextField.setText("");
        }
    }//GEN-LAST:event_RadioButtonSelected

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        
        //Initalize Values
        double massA;
        double massB;
        
        double velocityA = -1;
        double velocityA_ = -1;
        double velocityB = -1;
        double velocityB_ = -1;
           
        double directionA = 0;
        double directionA_ = 0;
        double directionB = 0;
        double directionB_= 0;
        
        Vector answer = null;
        StringBuilder stringAnswer = new StringBuilder();
        
        //Get Mass A & Mass B from JTextField
        try
        {
           massA = Double.parseDouble(massATextField.getText());
            if(massA == 0 || massA < 0)
               throw new Exception("The Mass for Object A Cannot be Zero or a Negative Value!");
        }
        catch (Exception ex)
        {
            System.err.println(ex.toString()); //Print Out Error to Console
            JOptionPane.showMessageDialog(this, "<html><b>The Mass for Object A is Invalid!</b><br>See Information/Help #3 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
            return;
        }
        try
        {
            massB = Double.parseDouble(massBTextField.getText());
            if(massB == 0 || massB < 0)
               throw new Exception("The Mass for Object B Cannot be Zero or a Negative Value!");
        }
        catch (Exception ex)
        {
            System.err.println(ex.toString()); //Print Out Error to Console
            JOptionPane.showMessageDialog(this, "<html><b>The Mass for Object B is Invalid!</b><br>See Information/Help #3 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
            return;
        }
        
        //Get Velocities and Directions from JTextField if the TextField is Enabled.
        if(veloInitATextField.isEnabled())
        {
            try
            {
                velocityA = Double.parseDouble(veloInitATextField.getText());
                if(velocityA < 0)
                   throw new Exception("The Inital Velocity for Object A Cannot be a Negative Value!");
            }
            catch (Exception ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Inital Velocity for Object A is Invalid!</b><br>See Information/Help #4 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
                return;
            }
            try
            {
                directionA = Double.parseDouble(dirInitATextField.getText());
            }
            catch (NumberFormatException ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Inital Direction for Object A is Invalid!</b><br>See Information/Help #5 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
                return;
            }
        }
        if(veloInitBTextField.isEnabled())
        {
            try
            {
                velocityB = Double.parseDouble(veloInitBTextField.getText());
                if(velocityB < 0)
                   throw new Exception("The Inital Velocity for Object B Cannot a Negative Value!");
            }
            catch (Exception ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Inital Velocity for Object B is Invalid!</b><br>See Information/Help #4 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
                return;
            }
            try
            {
                directionB = Double.parseDouble(dirInitBTextField.getText());
            }
            catch (NumberFormatException ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Inital Direction for Object B is Invalid!</b><br>See Information/Help #5 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
                return;
            }
        }
        if(veloFinATextField.isEnabled())
        {
           try
            {
                velocityA_ = Double.parseDouble(veloFinATextField.getText());
                if(velocityA_ < 0)
                   throw new Exception("The Post Collision Velocity for Object A Cannot a Negative Value!");
            }
            catch (Exception ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Post Collision Velocity for Object A is Invalid!</b><br>See Information/Help #4 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
                return;
            }
            try
            {
                directionA_ = Double.parseDouble(dirFinATextField.getText());
            }
            catch (NumberFormatException ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Post Collision Direction for Object A is Invalid!</b><br>See Information/Help #5 for more Details!</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
                return;
            }
        }
        if(veloFinBTextField.isEnabled())
        {
           try
            {
                velocityB_ = Double.parseDouble(veloFinBTextField.getText());
                if(velocityB_ < 0)
                   throw new Exception("The Post Collision Velocity for Object B Cannot be a Negative Value!");
            }
            catch (Exception ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Post Collision Velocity for Object B is Invalid!</b><br>See Information/Help #4 for more Details!", "Error!</html>", JOptionPane.WARNING_MESSAGE);        
                return;
            }
            try
            {
                directionB_ = Double.parseDouble(dirFinBTextField.getText());
            }
            catch (NumberFormatException ex)
            {
                System.err.println(ex.toString()); //Print Out Error to Console
                JOptionPane.showMessageDialog(this, "<html><b>The Post Collision Direction for Object B is Invalid!</b><br>See Information/Help #5 for more Details!", "Error!</html>", JOptionPane.WARNING_MESSAGE);        
                return;
            }
        }
        
        //Calculate Answer
        if(vectorInitACalcBtn.isSelected())
        {
            //Determine Total Momentum
            Vector A_ = new Vector((massA * velocityA_), directionA_, false);
            Vector B_ = new Vector((massB * velocityB_), directionB_, false);
            Vector total = Vector.addVectors(A_, B_);
            
            //Determine Missing Vector
            Vector B = new Vector((massB * velocityB), directionB + 180, false);
            answer = Vector.addVectors(total, B);
            
            //Create Answer String
            stringAnswer.append("The Initial Trajectory of Object A is: ");
            stringAnswer.append(Double.toString(answer.getMagnitude() / massA ));
            stringAnswer.append(" m/s [");
            stringAnswer.append(Double.toString(answer.getDirectionDeg()));
            stringAnswer.append("].");
        }
        else if(vectorInitBCalcBtn.isSelected())
        {
            //Determine Total Momentum
            Vector A_ = new Vector((massA * velocityA_), directionA_, false);
            Vector B_ = new Vector((massB * velocityB_), directionB_, false);
            Vector total = Vector.addVectors(A_, B_);
            
            //Determine Missing Vector
            Vector A = new Vector((massA * velocityA), directionA + 180, false);
            answer = Vector.addVectors(total, A);
            
            //Create Answer String
            stringAnswer.append("The Initial Trajectory of Object B is: ");
            stringAnswer.append(Double.toString(answer.getMagnitude() / massB ));
            stringAnswer.append(" m/s [");
            stringAnswer.append(Double.toString(answer.getDirectionDeg()));
            stringAnswer.append("].");
        }
        else if(vectorFinACalcBtn.isSelected())
        {
            //Determine Total Momentum
            Vector A = new Vector((massA * velocityA), directionA, false);
            Vector B = new Vector((massB * velocityB), directionB, false);
            Vector total = Vector.addVectors(A, B);
            
            //Determine Missing Trajectory
            Vector B_ = new Vector((massB * velocityB_), directionB_ + 180, false);
            answer = Vector.addVectors(total, B_);
            
            //Create Answer String
            stringAnswer.append("The Post Collision Trajectory of Object A is: ");
            stringAnswer.append(Double.toString(answer.getMagnitude() / massA));
            stringAnswer.append(" m/s [");
            stringAnswer.append(Double.toString(answer.getDirectionDeg()));
            stringAnswer.append("].");
        }    
        else if(vectorFinBCalcBtn.isSelected())
        {
            //Determine Total Momentum
            Vector A = new Vector((massA * velocityA), directionA, false);
            Vector B = new Vector((massB * velocityB), directionB, false);
            Vector total = Vector.addVectors(A, B);
            
            //Determine Missing Trajectory
            Vector A_ = new Vector((massA * velocityA_), directionA_ + 180, false);
            answer = Vector.addVectors(total, A_);
            
            //Create Answer String
            stringAnswer.append("The Post Collision Trajectory of Object B is: ");
            stringAnswer.append(Double.toString(answer.getMagnitude() / massB));
            stringAnswer.append(" m/s [");
            stringAnswer.append(Double.toString(answer.getDirectionDeg()));
            stringAnswer.append("].");
        }
        else
        {
            //Exception Handling - Nothing Was Selected To Solve
            System.err.println("Error: Nothing Was Selected To Solve!"); //Print Out Error to Console
            JOptionPane.showMessageDialog(this, "<html><b>Nothing Was Selected To Solve!</b><br>Please Select a Vector to Solve.</html>", "Error!", JOptionPane.WARNING_MESSAGE);        
            return;
        }
        JOptionPane.showMessageDialog(this, stringAnswer.toString(), "Answer", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void mainMenuRequested(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuRequested
        //Disable JFrame which will be disposed by calling class MomentumSolver
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuRequested
    
    //Custom Methods
     private void initMenuBar() {
        _menuBar = new JMenuBar();
        if(_isMacOS) //Mac Specific Setup
        {
           //Setup Menus
           _infoMenu = new JMenu("Information");
           _helpItem = new JMenuItem("Help");
           _infoMenu.add(_helpItem);
           _menuBar.add(_infoMenu);
           
           //Change Look & Feel for Popups
           try{ UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); }
           catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
           {
                JOptionPane.showMessageDialog(null, ex.toString(), "Error!",  JOptionPane.ERROR_MESSAGE);
			System.err.println(ex.toString()); 
           } //Show Pop-up Alert and Print Out Error to Console
           
           //Wire Up About Item
            try 
            {
                //Must be done using reflection otherwise will crash and not compile on other systems
                // See http://stackoverflow.com/questions/7256230/in-order-to-macify-a-java-app-to-catch-the-about-event-do-i-have-to-implement for more details
                //Pull Application Class
                Object thisApp = Class.forName("com.apple.eawt.Application").getMethod("getApplication",(Class[]) null).invoke(null, (Object[]) null);

                //Create a Instance of About Listener (Using Proxies)
                Object handleInstance = Proxy.newProxyInstance(Class.forName("com.apple.eawt.AboutHandler").getClassLoader(), new Class[] { Class.forName("com.apple.eawt.AboutHandler") }, new menu.AboutListenerMac());

                //Set Instance to Application Class
                thisApp.getClass().getMethod("setAboutHandler", new Class[] { Class.forName("com.apple.eawt.AboutHandler") }).invoke(thisApp, new Object[] { handleInstance });
            }
            catch(ClassNotFoundException | IllegalAccessException | NoSuchMethodException | InvocationTargetException ex)
            {
                JOptionPane.showMessageDialog(null, ex.toString(), "Error!",  JOptionPane.ERROR_MESSAGE);
                System.err.println(ex.toString()); 
            } //Show Pop-up Alert and Print Out Error to Console
        }
        else //Setup for All Other Systems
       {
           //Change Look & Feel
           try{ UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); }
           catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
           {
                JOptionPane.showMessageDialog(null, ex.toString(), "Error!",  JOptionPane.ERROR_MESSAGE);
			System.err.println(ex.toString()); 
           } //Show Pop-up Alert and Print Out Error to Console    

           //Setup Menus
           _infoMenu = new JMenu("Information");
           _aboutItem = new JMenuItem("About");
           _helpItem = new JMenuItem("Help");
           _infoMenu.add(_aboutItem);
           _infoMenu.add(_helpItem);
           _menuBar.add(_infoMenu);

           //Wire Up About Item
           _aboutItem.addActionListener( new menu.AboutMenuActionListener());
       }
       //Wire Up Help Item - System Independent
       _helpItem.addActionListener( new menu.HelpMenuActionListener());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateBtn;
    private javax.swing.JTextField dirFinATextField;
    private javax.swing.JLabel dirFinAUnitLabel;
    private javax.swing.JTextField dirFinBTextField;
    private javax.swing.JLabel dirFinBUnitLabel;
    private javax.swing.JTextField dirInitATextField;
    private javax.swing.JLabel dirInitAUnitLabel;
    private javax.swing.JTextField dirInitBTextField;
    private javax.swing.JLabel dirInitBUnitLabel;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JLabel massALabel;
    private javax.swing.JTextField massATextField;
    private javax.swing.JLabel massAUnitsLabel;
    private javax.swing.JLabel massBLabel;
    private javax.swing.JTextField massBTextField;
    private javax.swing.JLabel massBUnitsLabel;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JRadioButton vectorFinACalcBtn;
    private javax.swing.JRadioButton vectorFinBCalcBtn;
    private javax.swing.JRadioButton vectorInitACalcBtn;
    private javax.swing.JRadioButton vectorInitBCalcBtn;
    private javax.swing.JTextField veloFinATextField;
    private javax.swing.JLabel veloFinAUnitLabel;
    private javax.swing.JTextField veloFinBTextField;
    private javax.swing.JLabel veloFinBUnitLabel;
    private javax.swing.JTextField veloInitATextField;
    private javax.swing.JLabel veloInitAUnitLabel;
    private javax.swing.JTextField veloInitBTextField;
    private javax.swing.JLabel veloInitBUnitLabel;
    private javax.swing.ButtonGroup whichCalcGroup;
    // End of variables declaration//GEN-END:variables

}
